<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Poll') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<div class="page-header">
    <h1>
        <img src="<?php  echo $this->layoutAsset('icon/poll.png', 'image', 'poll') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />
        <?php echo $this->escapeHtml($this->pageTitle) ?>
    </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
    $this->baseTabs = [
        'list_questions' => [
            'name' => $this->translate('List of questions'),
            'controller' => 'polls-administration',
            'action' => 'list-questions',
            'check_acl' => true
        ]
    ]
?>