<?php $this->declareVars('content', 'extraActions', 'subPageTitle', 'parentPageTitle', 'currentPageTitle', 'processedQuestion') ?>
<?php $this->processedQuestion = mb_strlen($this->question['question']) < 60
    ? $this->question['question']
    : mb_substr($this->question['question'], 0, 60) . '...'
?>

<?php $this->parentPageTitle = $this->translate('List of questions') ?>
<?php $this->subPageTitle = $this->translate('Browse answers') ?>
<?php $this->currentPageTitle = $this->translate('Add an answer') ?>

<?php $this->headTitle($this->currentPageTitle) ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->processedQuestion) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('poll/poll-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-questions' // selected action is the "list-questions"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'polls-administration',
            'action' => 'list-questions',
            'check_acl' => true
        ],
        'browse_answers' => [
            'name' => $this->processedQuestion . ' - ' . $this->subPageTitle,
            'controller' => 'polls-administration',
            'action' => 'browse-answers',
            'params' => [
                'slug' => $this->question['id'],
            ],
            'check_acl' => true
        ],
        'add_answer' => [
            'name' => $this->currentPageTitle,
            'controller' => 'polls-administration',
            'action' => 'add-answer',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'polls-administration',
        'action' => 'edit-question',
        'params' => [
            'slug' => $this->question['id']
        ],
        'name' => $this->translate('Edit the question'),
        'check_acl' => true
    ],
    [
        'controller' => 'polls-administration',
        'action' => 'delete-questions',
        'name' => $this->translate('Delete the question'),
        'check_acl' => true,
        'confirm' => $this->translate('Question will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'questions' : [{$this->question['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'polls-administration', 'action' => 'list-questions'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'polls-administration',
        'action' => 'add-question',
        'name' => $this->translate('Add a question'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'title' => $this->translate('New answer'),
                'body' => $this->partial('partial/form', ['form' => $this->answer_form]),
                'notification' => false
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'title' => $this->translate('New answer'),
                'body' => $this->partial('partial/form', ['form' => $this->answer_form]),
                'notification' => false
            ]) ?>
        </div>
    <?php endif ?>
</div>