<style>
    .poll-wrapper ul {
        padding:0;
        margin-top:20px;
        margin-bottom:20px;
    }
    .poll-wrapper li {
        list-style: none;
        padding-top:10px;
    }
    .poll-wrapper .poll-date {
        float:left;
    }

    .poll-wrapper .poll-result {
        float:right;
    }
</style>


<div id="poll-wrapper-<?php echo (int) $this->connection_id ?>" class="poll-wrapper">
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <?php echo $this->escapeHtml($this->question_info['question']) ?>
            </h4>
            <div class="poll-values-wrapper">
                <?php echo $this->answers ?>
            </div>
            <div class="poll-date"><?php echo $this->applicationDate($this->question_info['created']) ?></div>
            <div class="poll-result">
                <a href="#">Result</a>
            </div>
            <div class="poll-result" style="display: none">
                <a href="#">Poll</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        /**
         * Poll
         *
         * @param array object options
         */
        Poll = function (options) {
            /**
             * Poll options
             *
             * @var array object
             */
            var pollOptions =
            {
                "url" : null,
                "wrapper_id": null,
                "values_wrapper" : null
            };

            // extend options
            pollOptions = $.extend({}, pollOptions, options);

            /**
             * Init
             */
            var init = function () {
                // make a vote
                $(pollOptions.wrapper_id).find(":input").click(function () {
                    $.post(pollOptions.url, {"widget_action" : "make_vote", "answer_id" : $(this).attr("data-id")}, function(data){
                        data =  $.parseJSON(data);

                        $(pollOptions.wrapper_id).find(pollOptions.values_wrapper).html(data.data);
                    });
                });
            }

            init();
        }

        var poll = new Poll({
            'url' : '<?php echo $this->escapeJs($this->widget_url) ?>',
            'wrapper_id': "#poll-wrapper-<?php echo (int) $this->connection_id ?>",
            'values_wrapper' : '.poll-values-wrapper'
        });
    });
</script>